blueprint:
  name: Telegram To-do List TEST
  description: >
    Базовый вариант:
    - edit_message только при реальном изменении
    - inline-кнопки обновляют сообщение
    - /list работает
    - защита от дублей
    - корректная обработка пустых действий (no-op)
    - HA 2025.12+
  domain: automation

  input:
    todo_entity:
      name: To-do список
      selector:
        entity:
          domain: todo

    telegram_chat_id:
      name: Telegram chat_id
      selector:
        number:

    bot_config_entry_id:
      name: Config Entry ID бота
      selector:
        text:

mode: restart
max_exceeded: silent

variables:
  todo_entity: !input todo_entity
  chat_id: !input telegram_chat_id
  bot_id: !input bot_config_entry_id

trigger:
  - platform: event
    event_type: telegram_command
  - platform: event
    event_type: telegram_text
  - platform: event
    event_type: telegram_callback

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.chat_id | int == chat_id | int }}

action:
  - choose:

      ############################################################
      # /start и /list — показать АКТИВНЫЕ
      ############################################################
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.event_type == 'telegram_command'
                 and trigger.event.data.command in ['/start','/list'] }}
        sequence:
          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            data:
              status: ['needs_action']
            response_variable: todo_resp

          - variables:
              items: "{{ todo_resp[todo_entity]['items'] | default([]) }}"
              text: >
                {% if items | length == 0 %}
                  🛒 Список покупок пуст 🤷‍♂️
                {% else %}
                  🛒 Список покупок:
                {% endif %}
              keyboard: >
                {% set r = namespace(v=[]) %}
                {% for i in items %}
                  {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                {% endfor %}
                {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                {% set r.v = r.v + [[['🗑 Очистить','/clear_completed']]] %}
                {{ r.v }}

          - action: telegram_bot.send_message
            data:
              config_entry_id: "{{ bot_id }}"
              chat_id: "{{ chat_id }}"
              message: "{{ text }}"
              inline_keyboard: "{{ keyboard }}"

      ############################################################
      # Добавление пункта текстом (С ЗАЩИТОЙ ОТ ДУБЛЕЙ)
      ############################################################
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.event_type == 'telegram_text'
                 and not (trigger.event.data.text | trim).startswith('/') }}
        sequence:
          - variables:
              new_item: "{{ trigger.event.data.text | trim }}"

          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            response_variable: current

          - variables:
              existing: >
                {{ current[todo_entity]['items']
                   | map(attribute='summary')
                   | map('lower')
                   | list }}
              is_duplicate: "{{ new_item | lower in existing }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_duplicate }}"
                sequence:
                  - action: telegram_bot.send_message
                    data:
                      config_entry_id: "{{ bot_id }}"
                      chat_id: "{{ chat_id }}"
                      message: "⚠️ Пункт «{{ new_item }}» уже есть в списке"

              - conditions:
                  - condition: template
                    value_template: "{{ not is_duplicate }}"
                sequence:
                  - action: todo.add_item
                    target:
                      entity_id: "{{ todo_entity }}"
                    data:
                      item: "{{ new_item }}"

                  - action: todo.get_items
                    target:
                      entity_id: "{{ todo_entity }}"
                    data:
                      status: ['needs_action']
                    response_variable: todo_resp

                  - variables:
                      items: "{{ todo_resp[todo_entity]['items'] }}"
                      text: "🛒 Список покупок:"
                      keyboard: >
                        {% set r = namespace(v=[]) %}
                        {% for i in items %}
                          {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                        {% endfor %}
                        {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                        {% set r.v = r.v + [[['🗑 Очистить','/clear_completed']]] %}
                        {{ r.v }}

                  - action: telegram_bot.send_message
                    data:
                      config_entry_id: "{{ bot_id }}"
                      chat_id: "{{ chat_id }}"
                      message: "{{ text }}"
                      inline_keyboard: "{{ keyboard }}"

      ############################################################
      # Inline-кнопки — DONE / CLEAR / SHOW ALL → edit_message
      ############################################################
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.event_type == 'telegram_callback' }}"
        sequence:
          - variables:
              cb: "{{ trigger.event.data.data }}"
              msg_id: "{{ trigger.event.data.message.message_id }}"
              mode: >
                {% if cb == '/show_all' %}all{% else %}active{% endif %}

          ##########################################################
          # DONE
          ##########################################################
          - if:
              - condition: template
                value_template: "{{ cb.startswith('/done_') }}"
            then:
              - action: todo.update_item
                target:
                  entity_id: "{{ todo_entity }}"
                data:
                  item: "{{ cb.split('_',1)[1] }}"
                  status: completed

          ##########################################################
          # CLEAR COMPLETED
          ##########################################################
          - if:
              - condition: template
                value_template: "{{ cb == '/clear_completed' }}"
            then:
              - action: todo.remove_completed_items
                target:
                  entity_id: "{{ todo_entity }}"

          ##########################################################
          # ЗАГРУЗКА СПИСКА (all / active)
          ##########################################################
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'all' }}"
                sequence:
                  - action: todo.get_items
                    target:
                      entity_id: "{{ todo_entity }}"
                    response_variable: todo_resp

              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'active' }}"
                sequence:
                  - action: todo.get_items
                    target:
                      entity_id: "{{ todo_entity }}"
                    data:
                      status: ['needs_action']
                    response_variable: todo_resp

          ##########################################################
          # РЕНДЕР
          ##########################################################
          - variables:
              items: "{{ todo_resp[todo_entity]['items'] | default([]) }}"
              text: >
                {% if items | length == 0 %}
                  🛒 Список покупок пуст 🤷‍♂️
                {% else %}
                  🛒 Список покупок:
                {% endif %}
              keyboard: >
                {% set r = namespace(v=[]) %}
                {% for i in items %}
                  {% if i.status == 'needs_action' %}
                    {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                  {% else %}
                    {% set r.v = r.v + [[['☑️ ' ~ i.summary, '/noop']]] %}
                  {% endif %}
                {% endfor %}
                {% if mode == 'active' %}
                  {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                {% else %}
                  {% set r.v = r.v + [[['▶ Активные','/show_active']]] %}
                {% endif %}
                {% set r.v = r.v + [[['🗑 Очистить','/clear_completed']]] %}
                {{ r.v }}

          ##########################################################
          # NO-OP → ТОЛЬКО УВЕДОМЛЕНИЕ, БЕЗ edit_message
          ##########################################################
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ cb == '/clear_completed' and items | length == 0 }}
                sequence:
                  - action: telegram_bot.answer_callback_query
                    data:
                      config_entry_id: "{{ bot_id }}"
                      callback_query_id: "{{ trigger.event.data.id }}"
                      message: "ℹ️ Список уже пуст"

              - conditions:
                  - condition: template
                    value_template: true
                sequence:
                  - action: telegram_bot.edit_message
                    data:
                      config_entry_id: "{{ bot_id }}"
                      chat_id: "{{ chat_id }}"
                      message_id: "{{ msg_id }}"
                      message: "{{ text }}"
                      inline_keyboard: "{{ keyboard }}"

                  - action: telegram_bot.answer_callback_query
                    data:
                      config_entry_id: "{{ bot_id }}"
                      callback_query_id: "{{ trigger.event.data.id }}"
                      message: "Готово"