blueprint:
  name: Telegram To-do List TEST
  description: >
    Рабочий вариант:
    - inline + edit_message
    - динамический переключатель Active / All
    - динамическая кнопка Очистить
    - визуальное различие active / completed
    - защита от дублей
    - HA 2025.12+
  domain: automation

  input:
    todo_entity:
      name: To-do список
      selector:
        entity:
          domain: todo

    telegram_chat_id:
      name: Telegram chat_id
      selector:
        number:

    bot_config_entry_id:
      name: Config Entry ID бота
      selector:
        text:

mode: restart
max_exceeded: silent

variables:
  todo_entity: !input todo_entity
  chat_id: !input telegram_chat_id
  bot_id: !input bot_config_entry_id

trigger:
  - platform: event
    event_type: telegram_command
  - platform: event
    event_type: telegram_text
  - platform: event
    event_type: telegram_callback

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.chat_id | int == chat_id | int }}

action:
  - choose:

      ############################################################
      # /start /list → ACTIVE
      ############################################################
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.event_type == 'telegram_command'
                 and trigger.event.data.command in ['/start','/list'] }}
        sequence:
          - variables:
              mode: active

          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            data:
              status: ['needs_action']
            response_variable: resp

          - variables:
              items: "{{ resp[todo_entity]['items'] | default([]) }}"
              has_items: "{{ items | length > 0 }}"
              text: >
                {% if not has_items %}
                  🛒 Список покупок пуст 🤷‍♂️
                {% else %}
                  🛒 Список покупок:
                {% endif %}
              keyboard: >
                {% set r = namespace(v=[]) %}
                {% for i in items %}
                  {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                {% endfor %}
                {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                {{ r.v }}

          - action: telegram_bot.send_message
            data:
              config_entry_id: "{{ bot_id }}"
              chat_id: "{{ chat_id }}"
              message: "{{ text }}"
              inline_keyboard: "{{ keyboard }}"

      ############################################################
      # Добавление пункта текстом (с защитой от дублей)
      ############################################################
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.event_type == 'telegram_text'
                 and not trigger.event.data.text.startswith('/') }}
        sequence:
          - variables:
              raw: "{{ trigger.event.data.text }}"
              norm: "{{ raw | lower | replace(' ', '') }}"

          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            response_variable: all

          - variables:
              found_active: >
                {{ all[todo_entity]['items']
                   | selectattr('status','eq','needs_action')
                   | map(attribute='summary')
                   | map('lower')
                   | map('replace',' ','')
                   | list
                   | select('equalto', norm)
                   | list | length > 0 }}

              found_completed: >
                {{ all[todo_entity]['items']
                   | selectattr('status','eq','completed')
                   | selectattr('summary','defined')
                   | map(attribute='summary')
                   | map('lower')
                   | map('replace',' ','')
                   | list
                   | select('equalto', norm)
                   | list | length > 0 }}

          - choose:
              ########################################################
              # Уже есть active
              ########################################################
              - conditions:
                  - condition: template
                    value_template: "{{ found_active }}"
                sequence:
                  - action: telegram_bot.send_message
                    data:
                      config_entry_id: "{{ bot_id }}"
                      chat_id: "{{ chat_id }}"
                      message: "⚠️ Такой пункт уже есть в списке"

              ########################################################
              # Есть completed → вернуть в active
              ########################################################
              - conditions:
                  - condition: template
                    value_template: "{{ found_completed }}"
                sequence:
                  - variables:
                      uid: >
                        {{ (all[todo_entity]['items']
                            | selectattr('status','eq','completed')
                            | selectattr('summary','defined')
                            | selectattr(
                                'summary',
                                'search',
                                raw | lower,
                                ignorecase=True
                              )
                            | list)[0].uid }}

                  - action: todo.update_item
                    target:
                      entity_id: "{{ todo_entity }}"
                    data:
                      item: "{{ uid }}"
                      status: needs_action

              ########################################################
              # Новый пункт
              ########################################################
              - conditions:
                  - condition: template
                    value_template: "{{ not found_active and not found_completed }}"
                sequence:
                  - action: todo.add_item
                    target:
                      entity_id: "{{ todo_entity }}"
                    data:
                      item: "{{ raw }}"

          ##########################################################
          # После любого успешного действия → показать список ACTIVE
          ##########################################################
          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            data:
              status: ['needs_action']
            response_variable: resp

          - variables:
              items: "{{ resp[todo_entity]['items'] }}"
              text: >
                {% if items | length == 0 %}
                  🛒 Список покупок пуст 🤷‍♂️
                {% else %}
                  🛒 Список покупок:
                {% endif %}
              keyboard: >
                {% set r = namespace(v=[]) %}
                {% for i in items %}
                  {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                {% endfor %}
                {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                {{ r.v }}

          - action: telegram_bot.send_message
            data:
              config_entry_id: "{{ bot_id }}"
              chat_id: "{{ chat_id }}"
              message: "{{ text }}"
              inline_keyboard: "{{ keyboard }}"

      ############################################################
      # CALLBACK: DONE / REOPEN / SHOW ALL / ACTIVE
      ############################################################
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.event_type == 'telegram_callback' }}"
        sequence:
          - variables:
              cb: "{{ trigger.event.data.data }}"
              msg_id: "{{ trigger.event.data.message.message_id }}"
              mode: >
                {% if cb == '/show_all' %}all{% else %}active{% endif %}

          - if:
              - condition: template
                value_template: "{{ cb.startswith('/done_') }}"
            then:
              - action: todo.update_item
                target:
                  entity_id: "{{ todo_entity }}"
                data:
                  item: "{{ cb.split('_',1)[1] }}"
                  status: completed

          - if:
              - condition: template
                value_template: "{{ cb.startswith('/reopen_') }}"
            then:
              - action: todo.update_item
                target:
                  entity_id: "{{ todo_entity }}"
                data:
                  item: "{{ cb.split('_',1)[1] }}"
                  status: needs_action

          - action: todo.get_items
            target:
              entity_id: "{{ todo_entity }}"
            response_variable: resp

          - variables:
              all_items: "{{ resp[todo_entity]['items'] }}"
              items: >
                {% if mode == 'all' %}
                  {{ all_items }}
                {% else %}
                  {{ all_items | selectattr('status','eq','needs_action') | list }}
                {% endif %}
              has_completed: >
                {{ all_items | selectattr('status','eq','completed') | list | length > 0 }}

              text: >
                {% if items | length == 0 %}
                  🛒 Список покупок пуст 🤷‍♂️
                {% else %}
                  🛒 Список покупок:
                {% endif %}

              keyboard: >
                {% set r = namespace(v=[]) %}
                {% for i in items %}
                  {% if i.status == 'needs_action' %}
                    {% set r.v = r.v + [[['✅ ' ~ i.summary, '/done_' ~ i.uid]]] %}
                  {% else %}
                    {% set r.v = r.v + [[['⬜ ' ~ i.summary, '/reopen_' ~ i.uid]]] %}
                  {% endif %}
                {% endfor %}
                {% if mode == 'active' %}
                  {% set r.v = r.v + [[['📂 Все','/show_all']]] %}
                {% else %}
                  {% set r.v = r.v + [[['▶ Активные','/show_active']]] %}
                {% endif %}
                {% if has_completed %}
                  {% set r.v = r.v + [[['🗑 Очистить','/clear_completed']]] %}
                {% endif %}
                {{ r.v }}

          - action: telegram_bot.edit_message
            data:
              config_entry_id: "{{ bot_id }}"
              chat_id: "{{ chat_id }}"
              message_id: "{{ msg_id }}"
              message: "{{ text }}"
              inline_keyboard: "{{ keyboard }}"

          - action: telegram_bot.answer_callback_query
            data:
              config_entry_id: "{{ bot_id }}"
              callback_query_id: "{{ trigger.event.data.id }}"
              message: "Готово"